//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3607
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XsdHelper.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XsdHelper.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xsd:schema id=&quot;Element_References_Other_Elements&quot;
        ///    targetNamespace=&quot;http://tempuri.org/Element_References_Other_Elements.xsd&quot;
        ///    elementFormDefault=&quot;qualified&quot;
        ///    xmlns=&quot;http://tempuri.org/Element_References_Other_Elements.xsd&quot;
        ///    xmlns:mstns=&quot;http://tempuri.org/Element_References_Other_Elements.xsd&quot;
        ///    xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///
        ///  &lt;xsd:element name=&quot;equity&quot; type=&quot;EquityAsset&quot; substitutionGroup=&quot;underlyingAsset&quot;&gt;
        ///    &lt;xsd:annotation [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Element_References_Complex_Types_Extensions_And_Groups {
            get {
                return ResourceManager.GetString("Element_References_Complex_Types_Extensions_And_Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xs:schema id=&quot;Element_References_Other_Elements&quot;
        ///    targetNamespace=&quot;http://tempuri.org/Element_References_Other_Elements.xsd&quot;
        ///    elementFormDefault=&quot;qualified&quot;
        ///    xmlns=&quot;http://tempuri.org/Element_References_Other_Elements.xsd&quot;
        ///    xmlns:mstns=&quot;http://tempuri.org/Element_References_Other_Elements.xsd&quot;
        ///    xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///
        ///  &lt;xs:element name=&quot;FirstLevelChild&quot;&gt;
        ///    &lt;xs:complexType&gt;
        ///      &lt;xs:sequence&gt;
        ///        &lt;xs:element ref=&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Element_References_Other_Elements {
            get {
                return ResourceManager.GetString("Element_References_Other_Elements", resourceCulture);
            }
        }
    }
}
